name: GitHub-Profile-3D-Contrib
on:
  schedule: # Runs at 18:00 UTC (3:00 JST) daily
    - cron: "0 18 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          # 1. Configure user identity
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # 2. Stage all generated files
          git add -A .
          
          # 3. Commit only if there are changes
          if git commit -m "generated" ; then
            # 4. Push the changes. Using 'git push' inside an action 
            # is a common practice for automated commits.
            git push
          else
            echo "No changes to commit, skipping push."
          fi
